require:
  - rubocop-rails
  - rubocop-rspec

# inherit_gem:
#   prettier: rubocop.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - "**/*.erb"
